Components
Christine-horrocks/shunter-api pull request #5
Opened 2018-05-21 10:03 UTC by Christine-horrocks

Rebase with development

2018-05-22 15:29 UTC, cazwazacz requested changes

2018-05-22 15:29 UTC, cazwazacz commented on .yardoc/checksums
> +app/jobs/application_job.rb 9a24c3e30cfb517943d8774df4695ba794bfd69d
Please add this to GitIgnore

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/block_component_serializer.rb
> +  class BlockComponentSerializer <BaseSerializer
Should this be? (missing space)
```ruby
class BlockComponentSerializer < BaseSerializer
```

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/block_component_serializer.rb
> +  class BlockComponentSerializer <BaseSerializer
Missing top level class documentation

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/block_component_serializer.rb
> +    def initialize(components, klass = 'block')
css class name?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/block_component_serializer.rb
> +    def initialize(components, klass = 'block')
Should this be a constant? To limit user's ability to do something weird

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/card_component_serializer.rb
> +  class CardComponentSerializer <BaseSerializer
same as above

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/card_component_serializer.rb
> +    # @param [Array<Hash>] an array of objects, each object is a component or atom.
Example?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/description_list_component_serializer.rb
> +
no space

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/heading_component_serializer.rb
> +
same as above

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/heading_component_serializer.rb
> +    # Initialise a paragraph component with a piece of text and an integer.
content vs test

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/heading_component_serializer.rb
> +
no space

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/heading_component_serializer.rb
> +
no space? see rubocop

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/image_component_serializer.rb
>      end
```ruby
      @figure_url = figure_url

      @image_src = image_src
      @image_alt = image_alt

      @image_srcset1 = image_srcset1
      @image_srcset2 = image_srcset2
```

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/list_component_serializer.rb
> +    # @param [Array<Hash>] an array of objects, each object is a component or atom.
example?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/list_component_serializer.rb
> +  class ListComponentSerializer <BaseSerializer
space?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/paragraph_component_serializer.rb
> +
spaces

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/roles_list_component_serializer.rb
> +    UL = 'ul'.freeze
Move these to list component

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/roles_list_component_serializer.rb
> +  class RolesListComponentSerializer < BaseComponentSerializer
This should inherit from list?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/roles_list_component_serializer.rb
> +    def initialize(current_roles, type='role', list_type=ComponentSerializer::RolesListComponentSerializer::UL, class_type = 'list--pipe')
```ruby
def initialize(current_roles, type='role', list_type=ComponentSerializer::ListComponentSerializer::UL, class_type = 'pipe')
```

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/component_serializer/section_primary_component_serializer.rb
> +
space?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +   @person.try(&:current_seat_incumbency).try(&:contact_points).each do |contact_point|
Error prone logic

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +    c << ComponentSerializer::ImageComponentSerializer.new(figure_url, image_srcset1, image_srcset2, image_src, image_alt).to_h if @person.image_id && @person.image_id != 'placeholder'
Maybe update to use srcset array?

 ```ruby
def image_srcset
    [
      generate_srcset(@person.image_id, 'CU_5:2', 732, 1464),
      generate_srcset(@person.image_id, 'MCU_3:2', 444, 888)
    ]
  end

  def generate_srcset(id, crop, small_width, large_width)
    small_src = generate_image_src(id, crop, small_width)
    large_src = generate_image_src(id, crop, large_width)
    
    "#{small_src}, #{large_src} 2x"
  end

  def generate_image_src(id, crop, width)
    "#{ENV['IMAGE_SERVICE_URL']}/#{id}.jpeg?crop=#{crop}&width=#{width}&quality=80"
  end
```

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +    c << ComponentSerializer::HeadingComponentSerializer.new(t('.people.related_links.title'), 2).to_h if @person.weblinks? || (@person.image_id && @person.image_id != 'placeholder')
could this use a constant?

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +    c << ComponentSerializer::HeadingComponentSerializer.new(t('.people.related_links.title'), 2).to_h if @person.weblinks? || (@person.image_id && @person.image_id != 'placeholder')
`ComponentSerializer::HeadingComponentSerializer::H2`

```ruby
ComponentSerializer::HeadingComponentSerializer.new('My Title', size: ComponentSerializer::HeadingComponentSerializer::H2).to_h 
```

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +    c << ComponentSerializer::HeadingComponentSerializer.new(t('.people.related_links.title'), 2).to_h if @person.weblinks? || (@person.image_id && @person.image_id != 'placeholder')
```ruby
ComponentSerializer::HeadingComponentSerializer.new('My Title', size: 2).to_h 
```

2018-05-22 15:29 UTC, cazwazacz commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +   @person.try(&:current_seat_incumbency).try(&:contact_points).each do |contact_point|
look at decorator default values

2018-05-23 09:15 UTC, Christine-horrocks commented on app/serializers/component_serializer/heading_component_serializer.rb
> +
Spaced both above and below according to the style guide

2018-05-23 09:32 UTC, Christine-horrocks commented on app/serializers/component_serializer/paragraph_component_serializer.rb
> +
The space between the end for the final method and the module and class ends is not in the style guide; however, is does make it much easier to read at a glance. I would ask to keep it.

2018-05-23 15:03 UTC, Christine-horrocks commented on app/serializers/component_serializer/roles_list_component_serializer.rb
> +    UL = 'ul'.freeze
Roles list component is extinct

2018-05-23 15:03 UTC, Christine-horrocks commented on app/serializers/component_serializer/roles_list_component_serializer.rb
> +  class RolesListComponentSerializer < BaseComponentSerializer
see above

2018-05-23 15:49 UTC, Christine-horrocks commented on app/serializers/page_serializer/person_show_page_serializer.rb
> +    c << ComponentSerializer::ImageComponentSerializer.new(figure_url, image_srcset1, image_srcset2, image_src, image_alt).to_h if @person.image_id && @person.image_id != 'placeholder'
Changed the whole thing into a hash

2018-05-25 10:08 UTC, cazwazacz approved these changes

2018-05-25 10:08 UTC, merged